### ISSUE TITLE
AuthenticateUser is vulnerable to SQL injection. 

### ISSUE THREAD

**Issue by ztsexton** [bradyscode/authentication-api#1]
https://github.com/bradyscode/authentication-api/blob/4096dd9803873c2e77f265d942ecf3fdc560423d/authentication-dot-net/Interfaces/UserInterface/UserInterface.cs#L29C8-L29C99

You are concatenating a string with data passed in from a user. Parameterized queries should be used here.

**Comment by bradyscode** [comment]
Hey Zach, this issue has been fixed in the following commit:
[SQL Injection in AuthenticateUser Method fix](https://github.com/bradyscode/authentication-api/commit/b4ddf2e0bde522f30779fe86df4bf761ec67e5bc)
